### ISSUE TITLE
Q se pueda cambiar calidades

### ISSUE THREAD

**Issue by joaquin-good** [danifreflow/Guts#5]
Q tenga una opción o agregar desde el scipt algo para q el anime se reproduzca en diferente calidades.

**Comment by mesteryui** [comment]
Si también sería bueno que permitiera mejorar la parte de seleccion de capitulos es decir que si no se el nombre del anime y lo selecciono por el menu me respete el numero de capitulo que he puesto como argumento del script

**Comment by danifreflow** [comment]
El tema de la mejora de las calidades depende de mpv, linkeo esto por si tu puede ayudar (https://github.com/mpv-player/mpv/issues/10169) . Respecto de la selección de capítulos, lo acabo de mejorar para que se pueda hacer. aunque no te sepas el nombre del anime. Estoy abierto a mejoras si se os ocurre algo, hacerme un pull request
