### ISSUE TITLE
[SUGERENCIA]: Añadir Licencia de código abierto para el repositorio

### ISSUE THREAD

**Issue by Inbydev** [danifreflow/Guts#7]
"Para que tu repositorio sea verdaderamente de código abierto, tendrás que generarle una licencia. De este modo, las demás personas podrán usar, modificar y distribuir el software con libertad. No tienes la obligación de elegir una licencia. Sin embargo, sin una licencia, se aplican las leyes de derecho de autor predeterminadas, lo que implica que conservas todos los derechos de tu código fuente, y nadie puede reproducir, distribuir o crear trabajos a partir de tu trabajo." [citado de documento github](https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by danifreflow** [comment]
Ya esta añadida una licencia, muchas gracias por tu aportación
