### ISSUE TITLE
Error de grep al abrir episodio 

### ISSUE THREAD

**Issue by siraprem** [danifreflow/Guts#8]
Despues de usar

Guts Lain 1

recibo:

1
grep: /tmp/jkanime.bz/um.php*: No existe el fichero o el directorio

**Comment by danifreflow** [comment]
Eso se puede deber a que el nombre del anime no este asi exactamente en jkanime, te recomiendo que pongas Lain solo para asi poder encontrar como se llama en la web , un saludo

**Comment by siraprem** [comment]
Solucionado, gracias
